print("hello world")
print("my favourite food is fried rice")
print("My birthday is on 31st jan 2014")
print("my name is Elara Griffin")
print(" i am 11 this year")
print("i am studying in Golden Gate Secondary School")
print("i will ")