print("hello world")
print("my favourite food is fried rice")
print("My birthday is on 31st jan 2014")
print("my name is Elara Griffin")
print(" i am 11 this year")
print("i am studying in Golden Gate Secondary School")
print("i will spend 2000 dollards on shares aka andvia")
#info given mite not be real :)
#activite 8
print("Wake up and get out of bed.")
print("Pour milk and cereal into a bowl.")
print("Eat your breakfast.")
#activite 9
print("Hello and how are you?")
print("What is wrong with this")
print("Why is this not working?")
print("Why is this not working?")